### PR TITLE
support multiple inverters for live data sync - fix #9

### LINKED ISSUE #9: Only one inverter data is counted for GW_STATION_ID
My GoodWe plant is composed of *two* inverters but the tool only uploads to pvoutput the data of one of them. While I would expect it to iterate over all inverters of the plant and sum the figures up (as is doing https://github.com/buttonfreak/goodwe-api)

For the rest, the tool is very sophisticated and working gracefully. Moreover the existence of a docker package let it install it ike a charm.

### PR DESCRIPTION
**Pull request by vijghph**
Loop over the additional inverters of a GoodWe plant to sum-up power and energy

### CODE REVIEW

**Comment by eNeRGy164** [comment]
I think this is a great start.

Things we might consider:
- [ ] The GW ID should become an optional parameter for the application, when not supplied, this code should be executed.
- [ ] If one GW ID is supplied as start-up parameter we should filter on this to keep the application backwards compatible. This is for people with multiple invertors that currently run the application with multiple PVO ID's.
- [ ] Optionally, we could support multiple GW ID's as parameters, filtering on several, but not all. This is new functionality.

**Comment by vijghph** [comment]
I have two inverters in a singe plant and the GWID relates to the plant, not the inverter.

I am not sure why we would like to support multiple GWID (except maybe for large companies having multiple plants)

**Comment by markruys** [comment]
I'll implement the summation of all online inverters, but I need a sample of what the call GetMonitorDetailByPowerstationId returns (use `--log debug` to get it). Most importantly, is eday and etotal per inverter?

**Comment by markruys** [comment]
I close this PR as I propose a slightly different approach. Please check out #19.

**Comment by markruys** [comment]
#19 is actually a different request. In #9 I propose a code change which supports multiple inverters.

**Pull request closed without merging**
